name: Publish Chatwoot CE docker images

on:
  workflow_dispatch:

jobs:
  publish-disabled:
    runs-on: ubuntu-latest
    steps:
      - name: Publishing disabled in public repo
        run: echo "Publishing moved to private repository Beedataco/beet-digital-apps."